import { Project } from '../types'

export const REGIONS = [
  { id: 'us', name: '美國', flag: '🇺🇸', currency: 'USD' },
  { id: 'eu', name: '歐洲', flag: '🇪🇺', currency: 'EUR' },
  { id: 'cn', name: '中國大陸', flag: '🇨🇳', currency: 'CNY' },
  { id: 'tw', name: '台灣', flag: '🇹🇼', currency: 'TWD' },
  { id: 'jp', name: '日本', flag: '🇯🇵', currency: 'JPY' },
  { id: 'in', name: '印度', flag: '🇮🇳', currency: 'INR' },
  { id: 'au', name: '澳洲', flag: '🇦🇺', currency: 'AUD' },
  { id: 'sea', name: '東南亞', flag: '🌏', currency: 'USD' },
]

export const DASHBOARD_STATS = {
  totalProjects: 12,
  activeProjects: 8,
  pendingApplications: 5,
  connectedTalents: 23,
  aiAssistCalls: 156,
  pendingMilestones: 7,
  totalSpent: 285000,
  completionRate: 94,
}

export const RECOMMENDED_TALENTS = [
  {
    id: '1',
    name: '王建國',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wang',
    role: '資深全棧工程師',
    skills: ['React', 'Node.js', 'Python', 'AI/ML'],
    rating: 4.9,
    completedProjects: 28,
    hourlyRate: 85,
    availability: 'available',
    matchScore: 95,
    region: '台灣',
    timezone: 'Asia/Taipei',
  },
  {
    id: '2',
    name: '李美華',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Li',
    role: 'UX 設計師',
    skills: ['Figma', 'UI Design', 'Prototyping', 'User Research'],
    rating: 4.8,
    completedProjects: 34,
    hourlyRate: 75,
    availability: 'busy',
    matchScore: 88,
    region: '新加坡',
    timezone: 'Asia/Singapore',
  },
  {
    id: '3',
    name: '陳志偉',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chen',
    role: '後端架構師',
    skills: ['Go', 'Kubernetes', 'System Design', 'PostgreSQL'],
    rating: 5.0,
    completedProjects: 19,
    hourlyRate: 120,
    availability: 'available',
    matchScore: 92,
    region: '日本',
    timezone: 'Asia/Tokyo',
  },
]

export const PENDING_TASKS = [
  {
    id: 't1',
    type: 'application',
    title: '新人才申請 (3)',
    description: '王建國申請參與智能客服項目',
    time: '2小時前',
    priority: 'high',
  },
  {
    id: 't2',
    type: 'milestone',
    title: '里程碑驗收 (1)',
    description: '「代碼開發里程碑」待驗收',
    time: '5小時前',
    priority: 'medium',
  },
  {
    id: 't3',
    type: 'message',
    title: '人才溝通回覆',
    description: '李美華詢問設計需求細節',
    time: '1天前',
    priority: 'low',
  },
  {
    id: 't4',
    type: 'ai',
    title: 'AI 成果審核 (2)',
    description: 'UX設計師AI輸出待確認',
    time: '1天前',
    priority: 'medium',
  },
  {
    id: 't5',
    type: 'payment',
    title: '里程碑結算',
    description: '「需求確認里程碑」待付款',
    time: '2天前',
    priority: 'high',
  },
]

export const ACTIVE_PROJECTS_MOCK = [
  {
    id: 'p1',
    title: '智能客服系統開發',
    status: 'in_progress',
    progress: 65,
    budget: 45000,
    spent: 29250,
    connectedTalents: 4,
    milestones: [
      { id: 'm1', name: '需求確認', status: 'completed', paid: true },
      { id: 'm2', name: '代碼開發', status: 'in_progress', paid: true },
      { id: 'm3', name: '測試驗收', status: 'pending', paid: false },
    ],
    aiAssistants: ['frontend_engineer', 'qa_engineer'],
    lastActivity: '2小時前',
  },
  {
    id: 'p2',
    title: '數據分析平台 UI/UX 優化',
    status: 'in_progress',
    progress: 40,
    budget: 28000,
    spent: 11200,
    connectedTalents: 2,
    milestones: [
      { id: 'm1', name: '設計調研', status: 'completed', paid: true },
      { id: 'm2', name: '原型設計', status: 'in_progress', paid: false },
      { id: 'm3', name: '交付驗收', status: 'pending', paid: false },
    ],
    aiAssistants: ['ux_designer'],
    lastActivity: '5小時前',
  },
]

export const MOCK_USERS = {
  project_initiator: {
    id: '1',
    name: '張偉明',
    email: 'initiator@codeutopia.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zhang',
    role: 'project_initiator',
    company: '創新科技有限公司',
    rating: 4.8,
    completedProjects: 12,
    balance: 45000,
    skills: ['項目管理', '產品設計'],
    verified: true,
    memberSince: '2024-03-15',
    location: '上海',
    timezone: 'Asia/Shanghai',
    bio: '專注於數位轉型的科技企業，尋找優質開發團隊合作',
    password: 'demo123',
  },
  contractor: {
    id: '2',
    name: 'Alex Chen',
    email: 'contractor@codeutopia.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    role: 'contractor',
    rating: 4.9,
    completedProjects: 35,
    balance: 12400,
    skills: ['React', 'Node.js', 'Python', 'AWS'],
    verified: true,
    memberSince: '2023-11-20',
    location: '新加坡',
    timezone: 'Asia/Singapore',
    bio: '全棧開發工程師，擁有豐富的跨國項目交付經驗',
    password: 'demo123',
  },
  webadmin: {
    id: 'admin1',
    name: 'System Admin',
    email: 'webadmin@codeutopia.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    role: 'webadmin',
    verified: true,
    memberSince: '2023-01-01',
    location: 'Global',
    timezone: 'UTC',
    rating: 0,
    completedProjects: 0,
    balance: 0,
    skills: [],
    bio: 'System Administrator',
    password: 'demo123',
  },
  regional_manager: {
    id: 'rm1',
    name: 'Sarah Lee',
    email: 'regional@codeutopia.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'regional_manager',
    location: 'Tokyo',
    timezone: 'Asia/Tokyo',
    verified: true,
    memberSince: '2023-06-15',
    rating: 5.0,
    completedProjects: 0,
    balance: 0,
    skills: ['Regional Management', 'Dispute Resolution'],
    bio: 'Regional Manager for APAC',
    password: 'demo123',
  },
}

export const TEST_ACCOUNTS = [
  {
    email: 'initiator@codeutopia.ai',
    password: 'demo123',
    role: 'project_initiator',
    roleName: '项目主理人',
    region: 'CHINA',
  },
  { email: 'contractor@codeutopia.ai', password: 'demo123', role: 'contractor', roleName: '接案者', region: 'APAC' },
  { email: 'webadmin@codeutopia.ai', password: 'demo123', role: 'webadmin', roleName: '全局管理员', region: 'GLOBAL' },
  {
    email: 'regional@codeutopia.ai',
    password: 'demo123',
    role: 'regional_manager',
    roleName: '区域主理人',
    region: 'APAC',
  },
]
